# Selecting and modifying elements with D3 {#d3intro}

## Selections

### Select by tag

The ability to select elements on a page is key to being able to manipulate them.  `d3.select()` will select the first match; `d3.selectAll()` will select all matches.

Chaining, similar to the tidyverse pipe operator `%>%`, allows us to act on the selected elements.  For example:

``` js
d3.select("circle");
```

selects the first circle in the order in which circles appear in the `<svg>` grouping. If there were more than one circle we could select them all with:

``` js
d3.selectAll("circle");
```

We can select HTML elements by tag in the same way:

``` js
d3.select("h1");
d3.selectAll("h1");
```

### Select by class

Classes are selected by adding a "." before the class name:

``` js
d3.selectAll("circle.legend")
```

This provides one method of selecting a certain collection of elements of the same type.

### Select by ID

IDs differ from classes in that they are unique identifies.  IDs are selected by adding a "#" before the ID:

``` js
d3.select("circle#henry");
```

## Modify existing elements

### Modifying attributes

[link to get or set attribute API](https://github.com/d3/d3-selection/blob/v1.4.0/README.md#selection_attr)

``` js
d3.select("circle").attr("r");           // see radius
d3.select("circle").attr("r", "10");     // set radius to 10
```


### Modifying styles

[link to get or set style API](https://github.com/d3/d3-selection/blob/v1.4.0/README.md#selection_style)

``` js
d3.select("h1").style("color");
d3.select("h1").style("color", "blue");
```

## Modifying text

### HTML text

``` html
<p id="typo">Manhatten</p>
```

<p id="typo">
Manhatten
</p>

Hover to execute this code (and fix the typo):

``` js
d3.select("#typo").text("Manhattan");
```

### SVG text
``` svg
<svg width="500" height="100">
  <rect width="500" height="100" fill="#326EA4"></rect>
<text id="svgtypo" x="50" y="70" fill="white"
    font-weight="bold" font-size="40px">
    Web scrapping is fun.</text>
</svg>  
```

<p style="font-size: 50%; line-height: 50%;">
svg
</p>
<svg width="500" height="100">
<rect width="500" height="100" fill="#326EA4"></rect> <text id="svgtypo" x="50" y="70" fill="white"
    font-weight="bold" font-size="40px"> Web scrapping is fun.</text>
</svg>
Hover to execute this code (and fix the typo):

``` js
d3.select("#svgtypo").text("Web scraping is fun.");
```


## Tips and tricks

1. The SVG `<text>` tag can be tricky.  It differs from HTML text tags (`<p>, <h1>, <h2>,` etc.) in that it has `x` and `y` attributes that allow you to position text on an SVG canvas.  Unlike HTML, the fill attribute controls the color of the text. Compare:
    
    ``` js
    d3.select("p").style("color", "red");   // HTML
    // with
    d3.select("text").attr("fill", "red");  // SVG
    ```

2. It is easy to confuse `.attr()` and `.style()`. <br> In general, properties such as position on the SVG, class, and ID are *attributes*, while decorative properties such as color, font, font size, etc. are *styles*.  However, in some cases, you can use either. For example, the following both make the circle blue:

    ``` js
    d3.select("circle").attr("fill", "blue");
    d3.select("circle").style("fill", "blue");
    ```
    
    The first will add a `fill="blue"` attribute to the `<circle>` tag, while the latter will add `style="fill: blue;"`. All is well and good until you find yourself with *both* in the same tag, in which case the `style` property will take precedence. The bottom line: don't mix the two options because it can cause problems.


3. To further complicat matters, `.style()` is just shorthand for `.attr("style", "...")` so 

Have any tips to add to this page? [Fork the repo, edit the page, and submit a pull request.](https://github.com/jtr13/d3book/edit/master/d3intro.Rmd){target="_blank"}

