# Introduction

Although it has plenty of new material and exercises, this book frequently references Scott Murray’s [*Interactive Data Visualization for the Web, 2nd edition*](https://www.amazon.com/Interactive-Data-Visualization-Web-Introduction/dp/1491921285/), a required book for GR5702. As such this resource is more a supplement to *IDVW2* rather than an alternative.

*IDVW2* is the gold standard for learning D3. You may be wondering, why do we need any extra material? Here's why:

- *IDVW2* is written for graphics designers not data science students so the pain points are somewhat different. As the title states, my intended audience is R users, though you certainly don't need to know R to use this resource.

- *IDVW2* does not use certain ES6 conventions which make coding easier (and more like R `r emo::ji("star_struck")`).

- *IDVW2* does not include examples involved advanced statistics.

- I prefer presenting some of the material in a different order than presented in *IDVW2*. 

None of this detracts from the fact that *IDVW2* is absolutely essential to learning D3. Although we will consider different examples, you are encouraged to study [Murray's code examples ](https://github.com/alignedleft/d3-book/releases){target="_blank"} in addition to reading the text.

