# Object Constancy <i class="fa fa-object-ungroup"></i> {#object}

## No object constancy

<script src="https://d3js.org/d3.v6.js"></script>

<table>
<tr><td>
<div id="chart"></div>
</td><td>
<p>**Transitions**</p>
<input type="radio" name="duration" class="noc" value="0" checked>&nbsp;Off</input>
<input type="radio" name="duration" class = "noc" value="750">&nbsp;On</input>
<p></p>
<p id="add" class="noc">Add bar</p>
<p id="remove_right" class="noc">Remove bar (right)</p>
<p id="remove_left" class="noc">Remove bar (left)</p>
</td></tr></table>

<script src="scripts/no_obj_const.js"></script>
<br>
**Of note:** 

* Rather than smoothly transitioning off to the left, all bars are resized when "Remove bar (left)" is clicked

* When "Remove bar (right) is clicked, the bar on the right immediately disappears, and then the remaining bars transition to their new places to the right.

Standalone version: [no_object_constancy.html](code/no_object_constancy.html)

## Object constancy
<table>
<tr><td>
<div id="chart2"></div>
</td><td>
<p>**Transitions**</p>
<input type="radio" name="duration2" class="oc" value="0" checked="true">&nbsp;Off</input>
<input type="radio" name="duration2" class = "oc" value="750">&nbsp;On</input>
<p></p>
<p id="add" class="oc">Add bar</p>
<p id="remove_right" class="oc">Remove bar (right)</p>
<p id="remove_left" class="oc">Remove bar (left)</p>
</td></tr></table>
<script src="scripts/obj_const.js"></script>

**Of note:** 

* Bars now smoothly transition off to the left and right

Standalone version: [object_constancy.html](code/object_constancy.html)

Slides: [object_constancy.pdf](pdfs/object_constancy.pdf){target="_blank"}


### Practice joining data by key

<div id="key"></div>

> <i class="fa fa-hand-o-right"></i> *Open the JavaScript Console* <i class="fa fa-terminal"></i>

Try the following:

1. Create an svg with four text elements:

``` js

var dataset = [{key: 12, x: 163, y: 200},
               {key: 14, x: 206, y: 304},
               {key: 16, x: 452, y: 152},
               {key: 18, x: 321, y: 254}];

var svg = d3.select("#key").append("svg")
		.attr("width", "600").attr("height", "400");

svg.append("rect").attr("width", "600")
		    .attr("height", "400").attr("fill", "aliceblue");

svg.selectAll("text")
		.data(dataset, d => d.key)
		.enter()
		.append("text")
		.attr("x", d => d.x)
		.attr("y", d => d.y)
		.text(d => `key: ${d.key}`);
```
		

2. Bind a new dataset by key:

``` js
var svg = d3.select("#key").select("svg");

var dataset = [{key: 12, x: 100, y: 200},
              {key: 16, x: 250, y: 300}];
              
svg.selectAll("text")
  .data(dataset, d => d.key)
  .exit()
  .remove();
```

Then:

``` js
svg.selectAll("text")
  .attr("x", d => d.x)
  .attr("y", d => d.y);
```

3. And another one:

``` js
var svg = d3.select("#key").select("svg");

var dataset = [{key: 23, x: 300, y: 150},
               {key: 5, x: 450, y: 270},
               {key: 16, x: 200, y: 250}];
              
var databind = svg.selectAll("text")
  .data(dataset, d => d.key);
  
databind  
  .enter()
  .append("text")
  .merge(databind)
  .attr("x", d => d.x)
  .attr("y", d => d.y)
  .text(d => `key: ${d.key}`);  
  
databind.exit().remove();
```

4. Experiment with other data binds.



